### PR TITLE
feat(components): rename notification components

### PR DESCRIPTION
**Pull request by connor-baer**
Addresses #469.

## Purpose

In the interest of consistency, the names of the notification components should be consistent.

## Approach and changes

- rename Message to Notification — _this brings it in line with the NotificationBanner and NotificationList_
- rename InlineNotification to InlineMessage — _this is to avoid confusion with the Notification components_

## Definition of done

* [x] Development completed
* [x] Reviewers assigned
* [x] Unit and integration tests
* [x] Meets minimum browser support
* [x] Meets accessibility requirements

### CODE REVIEW

**Comment by connor-baer** [comment]
Ping @robinmetral @dmitri-suvorov-sumup :)

**Comment by connor-baer** [comment]
@robinmetral @dmitri-suvorov-sumup

Travolta looking confused in Pulp Fiction

**Comment by robinmetral** [comment]
Sorry @connor-baer - missed this somehow. I'm on it!

**Comment by connor-baer** [comment]
@robinmetral Absolutely! This is based on the `alpha` (v2) branch. The breaking changes are described in the commit messages, which are automatically picked up by semantic-release and added to the release notes.

**Pull request merged**
