### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by connor-baer**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

# Releases

### Patch Changes

-   [#1593](https://github.com/sumup-oss/circuit-ui/pull/1593) [`da3cb509`](https://github.com/sumup-oss/circuit-ui/commit/da3cb509d6dfc58844a31937f37e772f01863030) Thanks [@tavarest](https://github.com/tavarest)! - Moved the `NfcPayment` icon to the payment methods category and changed its size to 24.
-   [#1593](https://github.com/sumup-oss/circuit-ui/pull/1593) [`da3cb509`](https://github.com/sumup-oss/circuit-ui/commit/da3cb509d6dfc58844a31937f37e772f01863030) Thanks [@tavarest](https://github.com/tavarest)! - Added the missing `viewbox` attribute to the `Boleto` and `Vr` icons.

### Patch Changes

- Updated dependencies [`701b9f4b`](https://github.com/sumup-oss/circuit-ui/commit/701b9f4b957cf0fb8bda0d5050b5f72747832422):
  - @sumup/icons@2.9.1

### CODE REVIEW

**Comment by tavarest** [comment]
@connor-baer according to [this comment](https://github.com/sumup-oss/circuit-ui/pull/1589#discussion_r890996877), should we also bump the circuit-ui version?

**Comment by connor-baer** [comment]
> @connor-baer according to [this comment](https://github.com/sumup-oss/circuit-ui/pull/1589#discussion_r890996877), should we also bump the circuit-ui version?

Yep, done in 99efc22.

**Comment by connor-baer** [comment]
> Why? 🤔 there's no change in Circuit UI, and it's still compatible with the same `@sumup/icons` version range. Why publish a new version, since that lengthens the `@sumup/circuit-ui` changelog and triggers dependabot/renovate/others in userland? I've been reverting these in the past

Did you see this https://github.com/sumup-oss/circuit-ui/pull/1589#discussion_r890996877? As far as I know, we've been downgrading the change type from `major` to `patch` when bumping peer dependencies in the past.

You're right that bumping the peer dependency wouldn't have been necessary for #1589 since the component library doesn't rely on the changes in the icon library. That's the approach that should have been taken ... and that's how we should have fixed it, now that I think about it 💡 We should have reverted the peer dependency bump. Lesson learned for next time!

**Comment by robinmetral** [comment]
Ah got it, thanks for context 🙌

**Pull request merged**
